services:
  toncenter-block-cacher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-ton}_block_cacher
    restart: unless-stopped
    hostname: toncenter-block-cacher
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "${DC_HTTP_PORT:-8080}:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # Limit each log file to 10 megabytes
        max-file: "3"      # Keep up to 3 log files
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/blocks/latest"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
